#!/bin/sh
OPENSSL=openssl

# Remove old files.
rm -f index.txt*
rm -f serial*
rm -f *.pem
rm -f *.key
rm -rf CA

# Create new CA directory
mkdir CA
mkdir CA/private
mkdir CA/certs

# Create the necesary files
touch CA/index.txt
echo 01 > CA/serial

# Do the work
cat banners/1 && $OPENSSL req -newkey rsa -keyout CA/private/cakey.pem -out CA/careq.pem -config conf/root.cnf
cat banners/2 && $OPENSSL ca -config conf/root.cnf -out root.pem -days 3650 -batch -keyfile CA/private/cakey.pem -selfsign -infiles CA/careq.pem

cat banners/3 && $OPENSSL req -newkey rsa -config conf/client.cnf -keyout client.pem -out newreq.pem -days 365
cat banners/4 && $OPENSSL ca  -config conf/root.cnf -batch -out newcert.pem -infiles newreq.pem
cat banners/5 && $OPENSSL rsa < client.pem > client.key
cat client.key newcert.pem > client.pem
rm -f client.key
rm -f newcert.pem
rm -f newreq.pem

cat banners/6 && $OPENSSL req -newkey rsa -config conf/server.cnf -keyout server.pem -out newreq.pem -days 365
cat banners/7 && $OPENSSL ca  -config conf/root.cnf -batch -out newcert.pem -infiles newreq.pem
cat banners/5 && $OPENSSL rsa < server.pem > server.key
cat server.key newcert.pem > server.pem
rm -f server.key
rm -f newcert.pem
rm -f newreq.pem
